// <auto-generated />
using System;
using FlightBookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260123185301_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("LetterId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("LetterId");

                    b.HasIndex("RowId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Rows")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("SeatsPerRow")
                        .HasMaxLength(26)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            RowNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            RowNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            RowNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            RowNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            RowNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            RowNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            RowNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            RowNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            RowNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            RowNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            RowNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            RowNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            RowNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            RowNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            RowNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            RowNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            RowNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            RowNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            RowNumber = 20
                        },
                        new
                        {
                            Id = 21,
                            RowNumber = 21
                        },
                        new
                        {
                            Id = 22,
                            RowNumber = 22
                        },
                        new
                        {
                            Id = 23,
                            RowNumber = 23
                        },
                        new
                        {
                            Id = 24,
                            RowNumber = 24
                        },
                        new
                        {
                            Id = 25,
                            RowNumber = 25
                        },
                        new
                        {
                            Id = 26,
                            RowNumber = 26
                        },
                        new
                        {
                            Id = 27,
                            RowNumber = 27
                        },
                        new
                        {
                            Id = 28,
                            RowNumber = 28
                        },
                        new
                        {
                            Id = 29,
                            RowNumber = 29
                        },
                        new
                        {
                            Id = 30,
                            RowNumber = 30
                        },
                        new
                        {
                            Id = 31,
                            RowNumber = 31
                        },
                        new
                        {
                            Id = 32,
                            RowNumber = 32
                        },
                        new
                        {
                            Id = 33,
                            RowNumber = 33
                        },
                        new
                        {
                            Id = 34,
                            RowNumber = 34
                        },
                        new
                        {
                            Id = 35,
                            RowNumber = 35
                        },
                        new
                        {
                            Id = 36,
                            RowNumber = 36
                        },
                        new
                        {
                            Id = 37,
                            RowNumber = 37
                        },
                        new
                        {
                            Id = 38,
                            RowNumber = 38
                        },
                        new
                        {
                            Id = 39,
                            RowNumber = 39
                        },
                        new
                        {
                            Id = 40,
                            RowNumber = 40
                        },
                        new
                        {
                            Id = 41,
                            RowNumber = 41
                        },
                        new
                        {
                            Id = 42,
                            RowNumber = 42
                        },
                        new
                        {
                            Id = 43,
                            RowNumber = 43
                        },
                        new
                        {
                            Id = 44,
                            RowNumber = 44
                        },
                        new
                        {
                            Id = 45,
                            RowNumber = 45
                        },
                        new
                        {
                            Id = 46,
                            RowNumber = 46
                        },
                        new
                        {
                            Id = 47,
                            RowNumber = 47
                        },
                        new
                        {
                            Id = 48,
                            RowNumber = 48
                        },
                        new
                        {
                            Id = 49,
                            RowNumber = 49
                        },
                        new
                        {
                            Id = 50,
                            RowNumber = 50
                        });
                });

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.SeatLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("Letter")
                        .IsUnique();

                    b.ToTable("SeatLetters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Letter = "A"
                        },
                        new
                        {
                            Id = 2,
                            Letter = "B"
                        },
                        new
                        {
                            Id = 3,
                            Letter = "C"
                        },
                        new
                        {
                            Id = 4,
                            Letter = "D"
                        },
                        new
                        {
                            Id = 5,
                            Letter = "E"
                        },
                        new
                        {
                            Id = 6,
                            Letter = "F"
                        },
                        new
                        {
                            Id = 7,
                            Letter = "G"
                        },
                        new
                        {
                            Id = 8,
                            Letter = "H"
                        },
                        new
                        {
                            Id = 9,
                            Letter = "I"
                        },
                        new
                        {
                            Id = 10,
                            Letter = "J"
                        },
                        new
                        {
                            Id = 11,
                            Letter = "K"
                        },
                        new
                        {
                            Id = 12,
                            Letter = "L"
                        },
                        new
                        {
                            Id = 13,
                            Letter = "M"
                        },
                        new
                        {
                            Id = 14,
                            Letter = "N"
                        },
                        new
                        {
                            Id = 15,
                            Letter = "O"
                        },
                        new
                        {
                            Id = 16,
                            Letter = "P"
                        },
                        new
                        {
                            Id = 17,
                            Letter = "Q"
                        },
                        new
                        {
                            Id = 18,
                            Letter = "R"
                        },
                        new
                        {
                            Id = 19,
                            Letter = "S"
                        },
                        new
                        {
                            Id = 20,
                            Letter = "T"
                        },
                        new
                        {
                            Id = 21,
                            Letter = "U"
                        },
                        new
                        {
                            Id = 22,
                            Letter = "V"
                        },
                        new
                        {
                            Id = 23,
                            Letter = "W"
                        },
                        new
                        {
                            Id = 24,
                            Letter = "X"
                        },
                        new
                        {
                            Id = 25,
                            Letter = "Y"
                        },
                        new
                        {
                            Id = 26,
                            Letter = "Z"
                        });
                });

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem.Domain.Entities.Booking", b =>
                {
                    b.HasOne("FlightBookingSystem.Domain.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Domain.Entities.SeatLetter", "Letter")
                        .WithMany()
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Domain.Entities.Row", "Row")
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Letter");

                    b.Navigation("Row");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlightBookingSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlightBookingSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlightBookingSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
